
### TEST GET / WEBSITE
GET http://localhost:3000


### TEST GET /dashboard WEBSITE
GET http://localhost:3000/dashboard


### DATA ENDPOINT
GET http://localhost:3000/api/data


### DATA ENDPOINT FOR ADDING A USER
POST http://localhost:3000/api/data
Content-Type: application/json

{
    "name": "Tommy"
}


### DELETE END POINT

DELETE http://localhost:3000/api/data
