### GET /
GET http://localhost:3000

### Register a user POST /auth/register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Log in a user POST /auth/login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}
